//
//  FEDashboardRouter.swift
//  FEProblem
//
//  Created by Nevilkumar Lad on 02/02/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FEDashboardRoutingLogic {
    func showNextScene()
}

protocol FEDashboardDataPassing {
    var dataStore: FEDashboardDataStore? { get }
}

class FEDashboardRouter: NSObject, FEDashboardRoutingLogic, FEDashboardDataPassing {
    weak var viewController: FEDashboardViewController?
    var dataStore: FEDashboardDataStore?

    // MARK: Navigation
    func showNextScene() {

    }
}

// MARK: Passing data
extension FEDashboardRouter {

    /*
    func passDataTo(_ destinationDS: inout <destinationDataStore>?, from sourceDS: FEDashboardDataStore?) {

    }
    */
}
