//
//  FEDashboardModels.swift
//  FEProblem
//
//  Created by Nevilkumar Lad on 02/02/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum FEDashboardLoaderType {
    case general
}

enum FEDashboardErrorType {
    case backend
    case custom(message: String)
}

enum FEDashboardModel {
    // MARK: Use cases

    enum FEDashboardDetails {
        struct Request {
        }
        struct Response {
        }
        struct ViewModel {
        }
    }

    enum NextScene {
        struct Request {
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
}
