//
//  FEDashboardWorker.swift
//  FEProblem
//
//  Created by Nevilkumar Lad on 02/02/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FEDashboardWorker {

    func getDestination() -> [Destination]? {
        if let mockData = AppUtility.sharedInstance.readLocalMockFile(forName: "Destinations") {
            if let decodeData = try? JSONDecoder().decode([Destination].self, from: mockData) {
                return decodeData
            }
       }
        return nil
    }
}
