//
//  FEDashboardInteractor.swift
//  FEProblem
//
//  Created by Nevilkumar Lad on 02/02/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FEDashboardBusinessLogic {
    func doFEDashboardDetails(request: FEDashboardModel.FEDashboardDetails.Request)
    func initialise(showLoader: Bool)
}

protocol FEDashboardDataStore {
    //var name: String { get set }
}

class FEDashboardInteractor: FEDashboardBusinessLogic, FEDashboardDataStore {
    var presenter: FEDashboardPresentationLogic?
    var worker: FEDashboardWorker?
    //var name: String = ""

    // MARK: Do FEDashboardDetails

    func doFEDashboardDetails(request: FEDashboardModel.FEDashboardDetails.Request)
    {
        worker = FEDashboardWorker()
        worker?.doSomeWork()

        let response = FEDashboardModel.FEDashboardDetails.Response()
        presenter?.presentFEDashboardDetails(response: response)
    }

    func initialise(showLoader: Bool = true) {
    }
}
