//
//  ListOptionsModels.swift
//  FEProblem
//
//  Created by Nevilkumar Lad on 03/02/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListOptionsLoaderType {
    case general
}

enum ListOptionsErrorType {
    case backend
    case custom(message: String)
}

enum ListOptionsModel {
    // MARK: Use cases

    enum ListOptionsDetails {
        struct Request {
        }
        struct Response {
        }
        struct ViewModel {
        }
    }

    enum ListOptions {
        struct Request {
        }

        struct Response {
            var selectableCell: Bool = false
            var items: [Any]
            var selectedItem: Destination?
        }

        struct ViewModel {
            struct DisplayedList {
                var title: String
                var subTitle: String
                var rightImage: String? = ""
                var leftImage: String? = ""
                var isSelcted: Bool = false
                var cellID: String = ""
            }
            var title: String
            var subTitle: String
            var planetName: String?
            var planetDistance: String?
            var isPlanetViewVisible: Bool = false
            var selectableCell: Bool = false
            var displayedList: [DisplayedList]
        }
    }

    enum NextScene {
        struct Request {
        }
        struct Response {
            let _id: Int64
            let selectionType: SelecionType
        }

        struct ViewModel {
            let _id: Int64
            let selectionType: SelecionType
        }
    }
}
