//
//  ListOptionsRouter.swift
//  FEProblem
//
//  Created by Nevilkumar Lad on 03/02/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


@objc protocol ListOptionsRoutingLogic {
    func showNextScene()
}

protocol ListOptionsDataPassing {
    var dataStore: ListOptionsDataStore? { get }
}

class ListOptionsRouter: NSObject, ListOptionsRoutingLogic, ListOptionsDataPassing {
    weak var viewController: ListOptionsViewController?
    var dataStore: ListOptionsDataStore?

    // MARK: Navigation
    func showNextScene() {

    }
}

// MARK: Passing data
extension ListOptionsRouter {

    /*
    func passDataTo(_ destinationDS: inout <destinationDataStore>?, from sourceDS: ListOptionsDataStore?) {

    }
    */
}
